podman-desktop/extension-minikube

- src/minikube-installer.ts
In the kind instructions, they _rename_ it after download...
https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries
But in minikube, it has the right name (.exe) from the start
Closes #9
> fix: unlike kind, minikube has a .exe extension

- package.json
- src/minikube-installer.spec.ts
- src/util.spec.ts
- src/util.ts
- yarn.lock
uses Podman Desktop API instead
fixes https://github.com/containers/podman-desktop-extension-minikube/issues/26
Change-Id: I8e3705a2d924c6ba61667ab8d814f5d50304dd2d
> fix: avoid the usage of sudo-prompt

- .github/workflows/build-next.yaml
- .github/workflows/release.yaml
I copied the release build from minikube when doing the bootc extension. We found a few small issues and made changes, so I am contributing them back. I've included all 4 changes since they are all small and on the same file, but I can split them up or remove some if requested.
line 51/78: Set the git email to be the person that kicked off the release (remove fbenoit hardcoding). Using a bot would be better, but this works for now.
line 87: Fixes the missing version in the description of the automated PR to bump version from e.g. "has been released." to "0.2.0 has been released."
line 96: Change the bumped version back before doing the build so that the correct version is in the released extension. e.g. today the released extension would be correctly tagged 0.2.0 but once you install it …
> fix: release build fixes

- package.json
- src/create-cluster.spec.ts
- src/create-cluster.ts
- src/extension.ts
- src/image-handler.spec.ts
- src/image-handler.ts
- src/minikube-installer.spec.ts
- src/util.spec.ts
- src/util.ts
- yarn.lock
This PR just updates the podman desktop api and replace the runCliCommand with the process.exec function from the api.
> fix: update podman api and replace local runCliCommand with process.exec

- src/extension.ts
This PR just pushes the statusBaritem to subscriptions so when the extension gets disactivated the item gets disposed and removed from the statusBar. This prevents having duplicates.
It resolves #21
> chore: push statusBarItem to subscriptions to be disposed correctly

- src/extension.spec.ts
- src/extension.ts
This resolves #45 
So far we were starting the existing minikube cluster just by starting/stopping the minikube container. Unfortunately this is not enough. Even though the container was started, the minikube cluster remained stopped. 
The minikube start command is responsible to start all features and handle all the process.
> fix: use minikube cli to start/stop cluster

- package.json
- src/create-cluster.spec.ts
- src/create-cluster.ts
- src/extension.spec.ts
- src/extension.ts
- src/image-handler.spec.ts
- src/image-handler.ts
- src/minikube-installer.spec.ts
- src/util.spec.ts
- src/util.ts
This is second try of making extension follows actual `MINIKUBE_HOME` instead of default.
[Previous context](https://github.com/containers/podman-desktop-extension-minikube/pull/34)
> Resolves #33 Add MINIKUBE_HOME configuration

- src/util.spec.ts
- src/util.ts
https://github.com/containers/podman-desktop-extension-minikube/pull/48 was merged but there was still a comment from @benoitf that was not fixed. This PR cleans up the tests
> fix: remove hoisted from test

- src/util.spec.ts
- src/util.ts
Adding utility methods required by https://github.com/containers/podman-desktop-extension-minikube/pull/156 and make smaller PR.
- Updating `installBinaryToSystem` to return the path where it installed the binary
- Adding `getBinarySystemPath` to have a single method deciding where the binary should be installed system-wide
- Adding `whereBinary` to detect the binary if installed system wide (copied from [podman-desktop#extensions/kind/src/util.ts#L97](https://github.com/containers/podman-desktop/blob/606d5c7010ad62699e867b0d077dcc6295a294dd/extensions/kind/src/util.ts#L97)
- Adding `deleteFile` which try to delete a file and if failed try with admin privilege (copy from [podman-desktop#extensions/kind/src/extension.ts#L489)](https://github.com/containers/podman-desktop/blob/85797008bdff9e …
> feat: adding utility methods for interacting with minikube executable

- src/download.spec.ts
- src/download.ts
- src/minikube-installer.ts
- src/util.spec.ts
- src/util.ts
Following https://github.com/containers/podman-desktop-extension-minikube/pull/165 simplification.
- Adding `findMinikube` util method. _What is the difference between `findMinikube` and `detectMinikube` ?
| `findMinikube` | `detectMinikube` |
| --- | --- |
| `findMinikube` detect binary installed by `MinikubeDownload` | `detectMinikube` detect binary installed by `MinikubeInstaller` |
> ⚠️ I cannot replace yet `detectMinikube` by `findMinikube` because the status bar still uses `MinikubeInstaller` to install the binary
-  `MinikubeInstaller` and `detectMinikube` are marked as `deprecated`
> ℹ️ Why marking them as deprecated ? Because we have duplicate logic, that will need to be removed, and I want to make small PR, so I will not delete and replace everything at once, so the follow-up PR …
> feat: adding find minikube util method

- src/download.spec.ts
- src/download.ts
Following https://github.com/containers/podman-desktop-extension-minikube/pull/171. Given the podman desktop core api, we need to have a function handling the user selection for the version to install.
To be able to provide the `CliToolInstaller#selectversion`[^1] function, we need to have the quick pick logic. As recommended in https://github.com/containers/podman-desktop-extension-minikube/pull/171#discussion_r1806230966 making the logic part of the minikubeDownload as it need the object to collect the releases. 
[^1]: https://podman-desktop.io/api/interfaces/CliToolInstaller#selectversion
> feat: adding select version function

- src/download.spec.ts
- src/download.ts
Following https://github.com/containers/podman-desktop-extension-minikube/pull/172
When we `CliTool#registerInstall` and `CliTool#registerUpdate` we need a method to download and install the binary, instead of repeating the code between those two object, we can create a unique method `install` taking the artifact as argument. Why ? Because we have a bit of logic: 
1. download
2. try to install system wide
3. if system success return system path otherwise return download path
And having this method avoid repeating the same lines.
> ℹ️ Trust the process... almost at the end :)
> feat: adding install method on minikube download

- src/util.spec.ts
- src/util.ts
Adding the last[^1] method required to be able to manage the lifecycle of the CLI Tool: When we `createCliTool` we need to provide the version, if we only provide the path, it will not be displayed in the CliTool. Therefore we need an utility method to get the version.
[^1]: Maybe I am lying, only the future will tell.
> feat: adding utility method to get minikube executable version

- src/extension.spec.ts
- src/extension.ts
1. minikube not installed
3. minikube installed
5. minikube update available
Fixes https://github.com/containers/podman-desktop-extension-minikube/issues/149
1. go to CLITool
2. assert minikube cli tool card is visible
3. uninstall if already installed
4. assert no minikube provider in the resource page
5. install through cli tool page minikube
6. assert minikube provider in resource page
> feat: cli tool register install

- .gitignore
- eslint.config.mjs
- package.json
- playwright.config.ts
- pnpm-lock.yaml
- tests/playwright/src/spec/minikube-extension.spec.ts
- tests/playwright/tsconfig.json
- vitest.config.js
This PR adds a test scenario for the minikube extension
https://github.com/containers/podman-desktop-extension-minikube/issues/137
- Clone the podman-desktop repo
- cd to podman-desktop folder
- Execute pnpm install
- Execute pnpm build
- Set environment variable executing: export PODMAN_DESKTOP_ARGS="/path/to/podman-desktop"
- Clone the podman-desktop-extension-minikube repo
- cd  to  podman-desktop-extension-minikube folder
- Execute pnpm install
- Execute pnpm test:e2e
> test: Implement extension installation and basic extension handling test scenario

- src/util.spec.ts
- src/util.ts
Add the missing additional envs to the minikube cli version check. 
Fixes https://github.com/podman-desktop/extension-minikube/issues/242
> fix: missing minikube home in version check

- src/util.spec.ts
- src/util.ts
Based on [this](https://github.com/podman-desktop/extension-minikube/issues/215#issuecomment-2488795392) and [this](https://github.com/podman-desktop/extension-minikube/issues/215#issuecomment-2489527077)
Minikube, by design, uses `KUBECONFIG` env variable to write it's cluster configuration.
Due to keeping consistency between tools around `kubectl` and `minikube` (e.g., start cluster via Podman UI and manage via cli), Podman Desktop Minikube extension should also use `KUBECONFIG` if defined for any `minikube` binary calls to avoid error E1120:
```
E1120 17:53:32.745267   45820 status.go:417] kubeconfig endpoint: get endpoint: "minikube" does not appear in $KUBECONFIG
```
> Add KUBECONFIG env into minikube calls

- package.json
- src/create-cluster.ts
Resolves https://github.com/podman-desktop/extension-minikube/issues/36
Just passing `--install-addons` and `--addons` if defined during cluster creation
P.S. i think cluster creation UI become to look heavier, but it's just an IMHO
> feat: add addons for minikube cluster creation

- .github/workflows/e2e-windows.yaml
issue: https://github.com/podman-desktop/extension-minikube/issues/240
> ci: create gha workflow to automate minikube e2e tests on windows

- .github/workflows/e2e-windows.yaml
What does this PR do?
Changes the name of the workflow, updates the mapt image version, extends the tags parameter to link the machine to the GitHub Actions execution.
UPD: ensures getting current HEAD version of the test framework
> chore(ci):  improve windows e2e tests workflow

- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
- .gitignore
- tests/playwright/src/model/core/types.ts
- tests/playwright/src/model/pages/minikube-cluster-creation-page.ts
- tests/playwright/src/spec/minikube-extension.spec.ts
- tests/playwright/src/utility/operations.ts
issue: https://github.com/podman-desktop/extension-minikube/issues/298
> test: minikube cluster e2e tests

- .github/workflows/e2e-main.yaml
What does this PR do?
fixes an issue where MINIKUBE_DRIVER was not recognized by correctly referencing it as env.MINIKUBE_DRIVER in the workflow
> chore: fix minikube workflow

- tests/playwright/src/spec/minikube-extension.spec.ts
What does this pr do?
Removes the Minikube cluster and all traces before closing the application
issue: https://github.com/podman-desktop/extension-minikube/issues/397
> chore(test):  Remove the Minikube cluster and all traces before closing the application

- .github/workflows/e2e-windows.yaml
**What does the PR do?**
Fixes the spot-excluded-regions parameter.
Updates the mapt image version.
> fix: fix windows workflow

- .github/workflows/e2e-kubernetes-main.yaml
- .github/workflows/e2e-windows.yaml
- package.json
- tests/playwright/package.json
- tests/playwright/src/spec/kubernetes.spec.ts
This PR introduces a new Kubernetes test scenario, enabling Kubernetes e2e tests to run using a Minikube cluster.  
This PR  must be merged after https://github.com/podman-desktop/extension-minikube/pull/514.  
Closes [#471](https://github.com/podman-desktop/extension-minikube/issues/471).  
Successfully tested on my fork: [GitHub Actions Run](https://github.com/amisskii/podman-desktop-extension-minikube/actions/runs/14219462771).
> test: new Kubernetes e2e tests setup with Minikube

- .github/workflows/e2e-kubernetes-main.yaml
- tests/playwright/resources/kubernetes/test-deployment-resource.yaml
- tests/playwright/src/spec/kubernetes.spec.ts
What does this pr do? 
Adds a new e2e test for a Kubernetes deployment resource using a Minikube cluster. The test also covers editing the deployment using the Kubernetes edit feature.
Issues: 
https://github.com/podman-desktop/extension-minikube/issues/468
https://github.com/podman-desktop/extension-minikube/issues/476
> chore(test): k8s deployment resource e2e test

- pnpm-lock.yaml
What does this pr do?
removes duplicate keys for packages in the pnpm-lock.yaml file
> chore: fix the pnpm-lockfile.yaml

- tests/playwright/src/spec/minikube-extension.spec.ts
What does this pr do?
Adds error handling to log issues without crashing the process. Increases the timeout for verifying if the extension is installed.
> chore(test): add error handling and extend extension verification timeout
