podman-desktop/extension-minikube

- Containerfile
fixes https://github.com/containers/podman-desktop-extension-minikube/issues/4
Change-Id: I55525642c6518aef920e0c3da46198c887d50b25
> fix: missing files in the extension

- src/extension.ts
* https://github.com/containers/podman-desktop/pull/3013
> chore: add description for minikube

- .github/workflows/release.yaml
- package.json
fixes https://github.com/containers/podman-desktop-extension-minikube/issues/15
Change-Id: I2e9fbca2cc65813f9a1635e18f58a01fe1fac046
> chore: add release script with GitHub action

- package.json
- src/create-cluster.spec.ts
- src/create-cluster.ts
fixes https://github.com/containers/podman-desktop-extension-minikube/issues/13
Change-Id: I0706aaa3c934aa71f30e2c1948f7811883fd12f5
> feat: add option to customize base image and add mount option

- package.json
- src/minikube-installer.spec.ts
- src/minikube-installer.ts
- src/util.spec.ts
- src/util.ts
- yarn.lock
make usage of Podman Desktop API instead
Change-Id: I77bc62ff4e77fb66a67524a325a62d0c70b74a8c
> chore: remove custom utility functions

- package.json
- src/minikube-installer.ts
- yarn.lock
Change-Id: I7b99ac8810b5fe6fa66f939c31e8b7f17178b23d
> chore: bump dependencies

- .github/workflows/pr-check.yaml
> chore(build): switch to macos-14

- .npmrc
fix performance issue with pnpm and extension development
> chore(pnpm): adding node-linker config

- src/create-cluster.ts
- src/extension.spec.ts
- src/extension.ts
- src/image-handler.spec.ts
- src/image-handler.ts
Fixing typecheck issues
Fixes https://github.com/podman-desktop/extension-minikube/issues/154
Required for https://github.com/podman-desktop/extension-minikube/pull/222
> fix: typecheck

- .github/workflows/pr-check.yaml
- package.json
> chore(pr-check): adding typecheck

- tests/playwright/src/spec/minikube-extension.spec.ts
What issues does this PR fix or reference?
https://github.com/podman-desktop/extension-minikube/issues/138
How to test this PR?
Clone the podman-desktop repo
cd to podman-desktop folder
Execute pnpm install
Execute pnpm build
Set environment variable executing: export PODMAN_DESKTOP_ARGS="/path/to/podman-desktop"
Clone the podman-desktop-extension-minikube repo
cd to podman-desktop-extension-minikube folder
Execute pnpm install
Execute pnpm test:e2e
> chore(test): minikube binary installation e2e test

- package.json
- src/create-cluster.spec.ts
- src/create-cluster.ts
Resolves https://github.com/podman-desktop/extension-minikube/issues/104
> feat: add nodes argument in cluster creation #104

- .github/workflows/pr-check.yaml
- package.json
- tests/playwright/package.json
- tests/playwright/playwright.config.ts
- tests/playwright/src/spec/minikube-extension.spec.ts
- tests/playwright/tsconfig.json
What issues does this PR fix or reference?
https://github.com/podman-desktop/extension-minikube/issues/140
> ci: automate e2e tests on PR check

- .github/workflows/e2e-main.yaml
What issues does this PR fix or reference?
https://github.com/podman-desktop/extension-minikube/issues/139
> ci: create gha workflow to automate e2e tests

- .github/dependabot.yml
the dependency is updated when running the test and also when other dependencies are updated so no need to have dependabot updating the version
Change-Id: Iff33ce2e99dfc84e635387c1e2f6cb7123444fe3
> chore: ignore @podman-desktop/tests-playwright

- pnpm-lock.yaml
Apparently I should wait longer for dependabot created PRs to update after merging one of the requests.
> fix: pnpm-lock.yaml errors

- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
What does this PR?
Adds missing step to e2e tests workflow
Issue: https://github.com/podman-desktop/extension-minikube/issues/425
> chore: add missing step to e2e tests workflow

- tests/playwright/src/spec/minikube-extension.spec.ts
What does this pr do?
Adds an e2e test for container deployment to the Minikube cluster
Issue: https://github.com/podman-desktop/extension-minikube/issues/299
> chore(test): deploy a container to the Minikube cluster e2e test

- .github/workflows/e2e-windows.yaml
What does this PR do?
Updates the Windows CI workflow to use latest image versions
Issue: https://github.com/podman-desktop/extension-minikube/issues/481
> ci: update windows E2E tests workflow with latest image versions

- pnpm-lock.yaml
Change-Id: Idcccaa8b3182922386b624ddd1d998998d43ea07
> chore: fix lock file (duplicated entries)

- .github/workflows/e2e-windows.yaml
workaround for https://github.com/redhat-developer/mapt/issues/451
> fix: exclude regions with unavailable resources during instance creation

- .github/workflows/e2e-windows.yaml
> fix: fix windows workflow

- tests/playwright/src/spec/minikube-extension.spec.ts
What does the PR do? 
Fixes k8s e2e tests
> chore(test): fix k8s e2e tests

- src/extension.spec.ts
- src/extension.ts
Signed-off-by: Sonia Sandler <ssandler@redhat.com>
Adds update info (when available) to the Minikube provider
Closes https://github.com/podman-desktop/podman-desktop/issues/11557
> chore: add update info to Minikube provider

- .github/workflows/e2e-kubernetes-main.yaml
What does this PR do?
Fixes the GHA Kubernetes workflow.
> chore(test): fix k8s workflow

- tests/playwright/src/spec/minikube-extension.spec.ts
What does this pr do? 
Terminates the Minikube process before closing the Electron app and formats the test spec.
Issue: 
https://github.com/podman-desktop/extension-minikube/issues/397
> chore(test): resolve worker teardown timeout issue

- .github/workflows/e2e-main.yaml
What does this pr do? 
fixes the e2e-main workflow
> chore(test): fix e2e-main workflow

- .github/workflows/e2e-windows.yaml
What does this pr do? 
Schedule E2E tests to run on Windows every Monday
> chore(test): run e2e windows tests on schedule

- package.json
- pnpm-lock.yaml
- tests/playwright/package.json
> chore(deps): remove unused dependencies, mainly electron

- .github/workflows/build-next.yaml
- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
- .github/workflows/release.yaml
This PR updates NodeJS to use LTS version.
Fixes #684
> fix(ci): update node to LTS
